[ WARN ] Failed to fetch value for field: Sym.Dev.MM_Cleaned_filepath
[ WARN ] Traceback (most recent call last):
  File "C:\EID_Replay\EID_Parry\Execution\Access_Data.py", line 58, in get_data
    field_value = eval(command)
                  ^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
AttributeError: module 'Data.Symphony.Dev' has no attribute 'MM_Cleaned_filepath'

[ WARN ] Failed to fetch value for field: Sym.Dev.MM_Cleaned_filepath
[ WARN ] Traceback (most recent call last):
  File "C:\EID_Replay\EID_Parry\Execution\Access_Data.py", line 58, in get_data
    field_value = eval(command)
                  ^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
AttributeError: module 'Data.Symphony.Dev' has no attribute 'MM_Cleaned_filepath'

[ WARN ] Failed to fetch value for field: Sym.Dev.MM_Cleaned_filename
[ WARN ] Traceback (most recent call last):
  File "C:\EID_Replay\EID_Parry\Execution\Access_Data.py", line 58, in get_data
    field_value = eval(command)
                  ^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
AttributeError: module 'Data.Symphony.Dev' has no attribute 'MM_Cleaned_filename'

[ WARN ] Failed to fetch value for field: Sym.Dev.MM_SAP_SERVER
[ WARN ] Traceback (most recent call last):
  File "C:\EID_Replay\EID_Parry\Execution\Access_Data.py", line 58, in get_data
    field_value = eval(command)
                  ^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
AttributeError: module 'Data.Symphony.Dev' has no attribute 'MM_SAP_SERVER'. Did you mean: 'SAP_SERVER'?

[ WARN ] Failed to fetch value for field: Sym.Dev.MM_SAP_SERVER
[ WARN ] Traceback (most recent call last):
  File "C:\Users\pimeidinfra\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\pimeidinfra\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 87] The parameter is incorrect

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\EID_Replay\EID_Parry\Execution\Access_Data.py", line 58, in get_data
    field_value = eval(command)
                  ^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
AttributeError: module 'Data.Symphony.Dev' has no attribute 'MM_SAP_SERVER'. Did you mean: 'SAP_SERVER'?

